title: "cericube IT 잡학 아카이브(준비중)"
description: "다양한 IT 지식과 학습 내용을 기록하고 정리하는 블로그입니다."
email: "cericube@naver.com"
url: "https://cericube.github.io"
baseurl: ""
lang: "ko-KR"
timezone: "Asia/Seoul"
permalink: /archives/:categories/:title/
markdown: kramdown
highlighter: rouge

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
